# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04afcb55db3e3ebe76e391cb061d0a76a01e7b7cc1aad5a02045691c79d161672dc5d0fe44842eed14bbe2b23a030933b3b108da5895b0e2ab758f28f46b16b8

test:
  secret_key_base: 8c4c21f1897605e9a31f914159bb4b445abe04e609103f61db2ed319f4dfad35e76dd91f834671388a97a40fe1db5ed3612b3147638092f080496a669dcad9ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
